/*
 * @lc app=leetcode id=389 lang=golang
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.87%)
 * Likes:    622
 * Dislikes: 255
 * Total Accepted:    170.4K
 * Total Submissions: 314.7K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */

// @lc code=start
// 54/54 cases passed (0 ms)
// Your runtime beats 100 % of golang submissions
// Your memory usage beats 100 % of golang submissions (2.2 MB)
func findTheDifference(s string, t string) byte {
	var res byte
    for i := 0; i < len(s); i++ {
		res ^= s[i]
		// res += s[i]
		//此处也可以用整数的加法 -- 但是此种方法需要注意可能溢出!
	}
	for i := 0; i < len(t); i++ {
		res ^= t[i]
		// res -= t[i]
	}
	return res
}
// @lc code=end

